### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by mraaroncruz** [hjhart/the_rotten_pirate#10]
This is happening in ruby 1.9.3 and 1.9.2 when I run `bundle exec rake execute`
When I run it with 1.8.7 I get #9

```
rake aborted!
undefined method `[]' for nil:NilClass
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/result.rb:26:in `initialize'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/base.rb:102:in `new'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/base.rb:102:in `block in next_page'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/base.rb:100:in `each_with_index'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/base.rb:100:in `next_page'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/torrent_api-0.2.6/lib/pirate_bay/base.rb:35:in `execute'
/Users/aaron/Repo/the_rotten_pirate/lib/the_rotten_pirate.rb:39:in `search_for_dvd'
/Users/aaron/Repo/the_rotten_pirate/lib/the_rotten_pirate.rb:73:in `block in execute'
/Users/aaron/Repo/the_rotten_pirate/lib/the_rotten_pirate.rb:72:in `each'
/Users/aaron/Repo/the_rotten_pirate/lib/the_rotten_pirate.rb:72:in `execute'
/Users/aaron/Repo/the_rotten_pirate/Rakefile:45:in `block in <top (required)>'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/aaron/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/bin/rake:19:in `load'
/Users/aaron/Repo/the_rotten_pirate/vendor/bundle/ruby/1.9.1/bin/rake:19:in `<main>'
Tasks: TOP => execute
```

**Comment by mraaroncruz** [comment]
Works with latest master
