### ISSUE TITLE
Math.log not backwards compatible with 1.8.7

### ISSUE THREAD

**Issue by hjhart** [hjhart/the_rotten_pirate#2]
Receiving this error in specs.

```
    3) Rank score should have a higher ranking if there are 10 9.125's than if there is 2 10s.
    Failure/Error: rank_higher.score.should > rank_lower.score
    ArgumentError:
    wrong number of arguments (2 for 1)
     # ./lib/rank.rb:13:in `log'
     # ./lib/rank.rb:13:in `score'
     # ./spec/rank_spec.rb:25
```

In Ruby 1.9.2 the second argument sets the base. Replicate for 1.8.7.

**Comment by hjhart** [comment]
If you're experiencing this error an upgrade to ruby 1.9.2 would fix this.
